### PR TITLE
[sidebar] Add functions back, at least some of them

### PR DESCRIPTION
**Pull request by Dignifiedquire**
@josevalim just for you :stuck_out_tongue_winking_eye: 

screen shot 2015-09-13 at 01 18 09

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
Can we merge this?! :D

**Comment by Dignifiedquire** [comment]
sure ;)

**Comment by josevalim** [comment]
Btw, this merge broke the build: https://travis-ci.org/elixir-lang/ex_doc/builds/80072989

**Comment by deansc** [comment]
@Dignifiedquire thanks so much for adding the functions back :+1: you're a magician :-)

**Pull request merged**
