### PR TITLE
Keep trailing periods in summaries

### LINKED ISSUE #975: Missing period at end of Summary entry
It appears that ex_doc grabs the first paragraph from each `@doc` entry to use in the Summary section. This seems reasonable, but it also elides any trailing period, which (IMHO) does not. If I choose to write in complete sentences, with appropriate punctuation, I don't think ex_doc should overrule me.

### PR DESCRIPTION
**Pull request by eksperimental**
Closes #975

/cc @richmorin

### CODE REVIEW

**Comment by eksperimental** [comment]
8840881210da130aa7aa53d0a6095f2bb5d01772 introduced this change. We were removing trailing semicolons as well.
This PR only reverts the changes to the periods.

**Comment by RichMorin** [comment]
Thanks for dealing with this (admittedly minor) issue!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
no worries @richmorin

**Pull request merged**
