### PR TITLE
WIP: EPUB format: Split TOC in groups

### PR DESCRIPTION
**Pull request by milmazz**
This is the first attempt to split the *Table of Contents* into groups, one thing that is missing is to keep the order as stated in `mix.exs`, I'll work on that asap.

Do we want to split also the Modules, Exceptions, and Protocols as in the HTML format in sidebar area? 

screen shot 2016-11-26 at 2 05 59 pm

### CODE REVIEW

**Comment by josevalim** [comment]
> Modules, Exceptions, and Protocols

I would say so. It feels a bit weird with them at the top level.

**Comment by milmazz** [comment]
@josevalim Sorry for the delay on this but recently my wife gave birth to an adorable baby girl, our first child :heart:

I'll close this PR temporarily and I hope to work on this issue soon ;)

**Comment by josevalim** [comment]
@milmazz congratulations!!!!!!!! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by milmazz** [comment]
@josevalim Thank you very much :girl:

**Comment by dignifiedquire** [comment]
@milmazz congrats!!!

**Comment by eksperimental** [comment]
@milmazz Felicitaciones por ser papá por primera vez!
Y Bienvenida a este Mundo! :heart:

**Pull request closed without merging**
