### PR TITLE
Make "View Source" to show actual definition

### LINKED ISSUE #334: Make "View Source" to show actual definition, not `@doc` attribute

### PR DESCRIPTION
**Pull request by lexmag**
Closes #334.

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
sorry, it is not working

```
$ make docs
==> elixir (compile)
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.1.0-beta" "lib/elixir/ebin" -m "Kernel" -u "https://github.com/elixir-lang/elixir" --source-ref "a96b1411e8e5b2d03229c9839e62b755d622545a"  -o doc/elixir -p http://elixir-lang.org/docs.html
** (ArgumentError) argument error
    lib/ex_doc/retriever.ex:242: ExDoc.Retriever.find_actual_line/3
    lib/ex_doc/retriever.ex:166: ExDoc.Retriever.get_function/6
    lib/ex_doc/retriever.ex:97: anonymous fn/8 in ExDoc.Retriever.generate_node/3
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/ex_doc/retriever.ex:96: ExDoc.Retriever.generate_node/3
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
```

**Comment by lexmag** [comment]
Seems we need special handling for `Kernel.SpecialForms`.

**Comment by josevalim** [comment]
Yeah, if we can't find the line, the one from docs should be used.

**Comment by eksperimental** [comment]
@lexmag sorry, but it is still not building, and I get the exact same error (same number of lines and everything)
Should I open a new issue, so we can keep track of it?

**Comment by lexmag** [comment]
@eksperimental no worries, hmm, I've just tried to build latest elixir docs and they are builded successfully. Could you check what sha of the latest commit you have in your local `ex_doc`?
If it's still a problem I could make a debugging patch for you.

**Comment by josevalim** [comment]
FWIW, ex_doc master and elixir master are building the docs fine here too.

**Comment by eksperimental** [comment]
I'd appreciate that.
```sh
ex_doc (master)
../ex_doc $ git rev-parse HEAD
65b0607e942ddec46cdfa0f298f9f388a52fdbc7

# elixir (master)
../elixir $ git rev-parse HEAD
af3b7e2352eae92d2bc548ea7cea953651bba64a
```

**Comment by josevalim** [comment]
silly question but did you run `mix compile`in exdoc after fetching?

**Comment by eksperimental** [comment]
@josevalim your question is not silly by myself :tired_face:
I think i ran `MIX_ENV=test mix` after testing it so many times with the previous bug that I messed up, 
I think i need to pin up a paper on my wall saying

**INSTRUCTIONS TO TEST ExDoc (before reporting any bugs)**
`MIX_ENV=test mix do clean, test; mix do clean, compile`


@lexmag it's all good now. thanks a lot for looking after this issue

**Comment by lexmag** [comment]
@eksperimental great, I'm always happy to help.

**Pull request merged**
