### PR TITLE
More styling improvements

### PR DESCRIPTION
**Pull request by Dignifiedquire**

### CODE REVIEW

**Comment by milmazz** [comment]
@Dignifiedquire Could you please fix the unit tests?

**Comment by Dignifiedquire** [comment]
wtf they were passing locally :/

**Comment by Dignifiedquire** [comment]
@milmazz no idea what to do, I ran `mix clean` deleted `_build´ and the tests are still passing locally

**Comment by josevalim** [comment]
Let me take a look.

**Comment by josevalim** [comment]
It is because it uses Elixir master and we changed the line reference in master. It is not your fault @Dignifiedquire. :D We should ExDoc to use a stable elixir version.

**Comment by josevalim** [comment]
We should be good now in master. This is good to merge anyway.

**Comment by milmazz** [comment]
@Dignifiedquire @josevalim Ok, I'll merge this into `new_design`, then later I'll apply a `rebase` with the latest changes from `master`.

**Pull request merged**
