### PR TITLE
Add favicon when logo option is present

### PR DESCRIPTION
**Pull request by gfvcastro**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by ericmj** [comment]
If the logo is not centered and inside a square image it will look a bit weird. Take a look at https://hexdocs.pm/phoenix and https://hexdocs.pm/ecto. Should we document this and fix the projects or is there some other way to solve it?

**Comment by josevalim** [comment]
Yup, we should probably have something to be exclusively the favicon.

**Comment by gfvcastro** [comment]
Good catch! If you want, I can send a new PR. 😄

**Comment by josevalim** [comment]
@gfvcastro I actually don't think anything is necessary. If people have a favicon file in the output directory that is enough, right?

**Comment by ericmj** [comment]
@josevalim If you don't specify a favicon in the `<head>` I believe it will be fetched from the root which wont work for packages.

**Comment by josevalim** [comment]
Good point. Any ideas on how to solve this though? Should we have a favicon configuration like we do for the logo?

**Comment by gfvcastro** [comment]
@josevalim I think it is a good solution.

**Pull request merged**
