### PR TITLE
Don't allow selecting iex> in doctests

### LINKED ISSUE #835: Don't allow selecting iex> in doctests
Today copying from doctests is a bit annoying, especially if there are multiple lines involved, because you'll also select the `iex>` or `...>` parts.

It would be great, if we could make it so that those parts are skipped over when you try to select and copy the code from examples. I did a little research and it seems it's possible to do this in css with `user-select: none`, but I'm not really sure how to integrate it into the ex_doc pipeline.

### PR DESCRIPTION
**Pull request by nscyclone**
Closes #835.

<details>
<summary>Example</summary>

example

</details>

### CODE REVIEW

**Comment by josevalim** [comment]
This is awesome! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

I know this is a nitpick but... would it be possible to also include the first space in the "no select" area? Or would that impact users if they don't include any space between `iex>` and the code snippet?

/cc @michalmuskala

**Comment by nscyclone** [comment]
Thanks, @josevalim! I've just updated the branch.

<details>
<summary>Now the result looks like this:</summary>


example

</details>

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by wojtekmach** [comment]
This is awesome 👏

**Comment by michalmuskala** [comment]
Thank you! ❤️

**Pull request merged**
