### PR TITLE
Add pre-commit checks

### LINKED ISSUE #268: Check the commit for non-updated dist files (when apply)
Right now in the `build_system` branch you can find the ready to use CSS/JS versions in `lib/ex_doc/formatter/html/templates/dist`

One thing that we need to guarantee is that every time that somebody update a css/js file (located under `assets` directory), the files under the `dist` directory also gets updated.

We can try to guarantee this via a git hook (`pre-commit`)

### PR DESCRIPTION
**Pull request by milmazz**
This proposal automatically install pre-commit hooks, only apply for the JS/CSS part. Task that we run on each pre-commit:

 * Verify the quality of the JS code
 * Run some tests
 * Prepare the distribution (or minified) files

Closes #268 

/cc @Dignifiedquire

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Please use the local version of gulp `node_modules/gulp/bin/gulp` that way it doesn't rely on binaries in your path

**Comment by Dignifiedquire** [comment]
Other than that it looks good :

**Comment by milmazz** [comment]
@Dignifiedquire Thanks for the review, now we're using the local version of gulp as you suggested :)

**Comment by eksperimental** [comment]
While developing, sometimes I need to do a commit --amend or simply I don't want to run the test. How can I bypass this?

**Comment by eksperimental** [comment]
answering myself, as I just found out. pass the `--no-verify` or `-n` option. to git.
such as:
`git commit -a --amend --no-verify`

**Comment by eksperimental** [comment]
@milmazz just to be sure.
I don't need to worry about anymore running `gulp build --type production` with this new feature. am i right?

**Comment by milmazz** [comment]
@eksperimental Yes, you are right, the `pre-commit` process will take care of that for you (`lint`-> `test` -> `build --type production`), unless you put the `--no-verify` option :grin:

**Comment by eksperimental** [comment]
this is so convenient. thank you for the PR!

**Comment by eksperimental** [comment]
@milmazz correct me if I'm wrong, but I ran this yesterday and I noticed the app.js was generated, but it remained unstaged. it was not part of the commit.

**Comment by eksperimental** [comment]
```
$ git status
On branch sidebar_links_handlebar
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   assets/js/template-helpers/isNotLocal.js
	modified:   assets/js/templates/sidebar-items.handlebars

$ git commit
[20:57:00] Using gulpfile ./ex_doc/gulpfile.js
[20:57:00] Starting 'lint'...
[20:57:07] Finished 'lint' after 6.35 s
[20:57:13] Using gulpfile ./ex_doc/gulpfile.js
[20:57:13] Starting 'test'...
21 09 2015 20:57:23.610:INFO [karma]: Karma v0.13.9 server started at http://localhost:9876/
21 09 2015 20:57:23.637:INFO [launcher]: Starting browser Chrome
21 09 2015 20:57:29.068:INFO [Chromium 43.0.2357 (Ubuntu 0.0.0)]: Connected on socket zGR2Lk_s7ds6ubZQAAAA with id 98572541
Chromium 43.0.2357 (Ubuntu 0.0.0): Executed 7 of 7 SUCCESS (0.119 secs / 0.021 secs)
[20:57:31] Finished 'test' after 18 s
[20:57:37] Using gulpfile ./ex_doc/gulpfile.js
[20:57:37] Starting 'build'...
[20:57:37] Starting 'clean'...
[20:57:37] Finished 'clean' after 35 ms
[20:57:37] Starting 'buildHighlight'...
[20:57:37] Starting 'less'...
[20:57:40] less all files 15.66 kB
[20:57:40] Finished 'less' after 3.07 s
[20:57:44] Finished 'buildHighlight' after 6.76 s
[20:57:44] Starting 'javascript'...
[20:58:14] Version: webpack 1.12.1
 Asset    Size  Chunks             Chunk Names
app.js  542 kB       0  [emitted]  main
[20:58:14] js all files 164.42 kB
[20:58:14] Finished 'javascript' after 30 s
[20:58:14] Finished 'build' after 37 s
```

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch sidebar_links_handlebar
# Changes to be committed:
#       new file:   assets/js/template-helpers/isNotLocal.js
#       modified:   assets/js/templates/sidebar-items.handlebars
```

```
[sidebar_links_handlebar fc16c37] Create proper links in sidebar handlebar template
 2 files changed, 21 insertions(+), 16 deletions(-)
 create mode 100644 assets/js/template-helpers/isNotLocal.js

$ git status
On branch sidebar_links_handlebar
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   lib/ex_doc/formatter/html/templates/dist/app.js
```

you can see after the commit was executed, you can see the modified app.js file

I think before commiting we need to run
`git add lib/ex_doc/formatter/html/templates/dist/`

**Comment by Dignifiedquire** [comment]
Running the build in the pre-commit hook does not ensure it gets committed atm. And I don't think there is an easy way to actually to that, but I might be wrong. I guess the best thing would to check if the build output is identical with what's already there and then fail the hook if it isn't

**Comment by eksperimental** [comment]
from what I was able to see, it is pretty commong for a pre-commit to run something like `git add lib/ex_doc/formatter/html/templates/dist/app.js` and app.css on a pre-commit.

**Comment by Dignifiedquire** [comment]
Okay, if that's so, I'm happy to add that

**Comment by eksperimental** [comment]
we need to run:
```
git add lib/ex_doc/formatter/html/templates/dist/app.js
git add lib/ex_doc/formatter/html/templates/dist/app.css
```

I don't really know how the JS packages work, so it's better if one of you guys try it out.

**Pull request merged**
