### PR TITLE
Generate JSON file with all the sidebar items info

### LINKED ISSUE #495: Generate JSON file with index of all modules and functions
Currently there is no way find all modules and functions without scraping the generated docs, which is difficult to say the least and not backwards compatible. An index file would make it much easier for external tools that want to implement search on documentation.

JSON files with the docs and specs would also be good to have.

### PR DESCRIPTION
**Pull request by milmazz**
From now on, with the new `sidebar_items.json`, 3rd party applications should find a list with all the exceptions, modules, protocols and additional documentation without scrapping the generated docs. Fixes #495 

/cc @Dignifiedquire @ericmj

### CODE REVIEW

**Comment by ericmj** [comment]
Hum, I am afraid this will affect page load time since we are doing an ajax call instead of loading it from a script tag, but I haven't measured so I can't know for sure.

Maybe it would be better to have the JSON as a separate file? This file could also include the full docs since it wouldn't be loaded on each request.

**Comment by josevalim** [comment]
And the issue with JSON call is that it won't work when using the file protocol. If we are going to generate the JSON thing, it needs to be an extra file or an special command, I don't think we should add it to the generated code.

> Maybe it would be better to have the JSON as a separate file? This file could also include the full docs since it wouldn't be loaded on each request.

Honestly, that doesn't feel like the job of ex_doc or maybe just a custom json formatter. This information can be extracted from the elixir code anyway.

**Comment by ericmj** [comment]
> Honestly, that doesn't feel like the job of ex_doc or maybe just a custom json formatter. This information can be extracted from the elixir code anyway.

Then you have to compile the code. For an external tool to do that, you need to figure the OTP and elixir version that works for compiling the project, you have to fetch dependencies and compile the project. And compiling code executes arbitrary code so you need to figure out a way to sandbox it. Then scraping the HTML is much, much easier.

This is exactly why hexdocs make you upload HTML instead of automatically generating docs for you, because it's impossible to do reliably.

I don't see why ex_doc can't generate this when all the information is already and it already generates the exact file we need except for ~10 chars extra.

**Comment by josevalim** [comment]
There are a couple things:

1. The 10 extra chars are what makes it work for ExDoc

2. What it generates is private, meant to be consumed by ExDoc itself. I am
not comfortable in any way to make it public. I don't want to maintain that
format forever if we decide to rewrite ExDoc internals into something that
makes more sense for ExDoc

3. That's why I was thinking it should at least be a JSON formatter thing
than just emit extra files in the HTML one

On Saturday, December 5, 2015, Eric Meadows-Jönsson <
notifications@github.com> wrote:

> Honestly, that doesn't feel like the job of ex_doc or maybe just a custom
> json formatter. This information can be extracted from the elixir code
> anyway.
>
> Then you have to compile the code. For an external tool to do that, you
> need to figure the OTP and elixir version that works for compiling the
> project, you have to fetch dependencies and compile the project. And
> compiling code executes arbitrary code so you need to figure out a way to
> sandbox it. Then scraping the HTML is much, much easier.
>
> This is exactly why hexdocs make you upload HTML instead of automatically
> generating docs for you, because it's impossible to do reliably.
>
> I don't see why ex_doc can't generate this when all the information is
> already and it already generates the exact file we need except for ~10
> chars extra.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ex_doc/pull/496#issuecomment-162169202>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
If we can have a JSON formatter as part of ex_doc and it runs when docs are published to hexdocs I would be happy.

**Comment by josevalim** [comment]
Ah, you want it as part of hexdocs? Why?

On Saturday, December 5, 2015, Eric Meadows-Jönsson <
notifications@github.com> wrote:

> If we can have a JSON formatter as part of ex_doc and it runs when docs
> are published to hexdocs I would be happy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ex_doc/pull/496#issuecomment-162172659>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
So that tooling can implement search on all hexdocs projects or use it create documentation in their own formats. Today there is no easy way to do that, you have to either scrape hexdocs or compile the project and both solutions have obvious issues.

**Comment by milmazz** [comment]
From @ericmj:

> Hum, I am afraid this will affect page load time since we are doing an ajax call instead of loading it from a script tag, but I haven't measured so I can't know for sure.

I made a few tests yesterday on Firefox and Chrome (OS X), and this method is more efficient than the previous one, this includes the first load and the subsequent ones.

> Maybe it would be better to have the JSON as a separate file? This file could also include the full docs since it wouldn't be loaded on each request.

If you want to provide access to all the documentation as JSON maybe the best approach is create a new formatter and then `mix hex.docs` will call `ex_doc` with both formatters (`html` and `json`)

From @josevalim 

> And the issue with JSON call is that it won't work when using the file protocol.

That's not true, `$.getJSON` works with the `file:///` protocol, I tested this on Firefox and Safari. With Chrome is another history, actually it's a [bug](https://code.google.com/p/chromium/issues/detail?id=40787) from 2010 and they don't have any plans to solve it, but you can launch Chrome with the option `--allow-file-access-from-files` and everything it's fine, I tested this in Chrome Canary and it works like a charm.

**Comment by ericmj** [comment]
Thanks for your work @milmazz. I talked to @josevalim and we have decided to rethink this and explore other approaches before we decide on one.

**Comment by milmazz** [comment]
@ericmj I think this PR should be reopened, why? As I mention before, even if you consider that this PR is not the definitive fix to provide a JSON file with all the information in the sidebar area you should consider the performance gain in the first and subsequent calls as I mentioned before.

May I ask why do you and @josevalim reject this PR?, It would be useful, at least for me, to know why do you reject this proposal (maybe I'm missing something here) and I'm also interested to know which other approaches have you discussed, in the end, as you may know, I just want to help to improve ExDoc.

**Comment by josevalim** [comment]
@milmazz what we generate is private, meant to be consumed by ExDoc itself. I am not comfortable with making it public in any way. Maybe we can merge this on the merits of making things faster but I would prefer to have it working on the file system across all browsers, specially given we are adding a feature to Hex that allow docs to be downloaded and placed locally. Saying it doesn't work on Chrome or  that it requires flags is a non-ideal solution imo.

**Comment by milmazz** [comment]
_Sorry_ for being so stubborn.

I know that you're afraid of making public this object as JSON, or you're afraid about the maintenance issues after releasing this, I know that. But IMHO the good thing is that ExDoc is pre-1.0. So, if the maintenance process is getting difficult at some point we can just deprecate the public stuff and that's it, some people going to cry, but you know, life isn't easy, the good thing is that at some point of their lives they will overcome their sadness ;)

I'm thinking that ExDoc could offer a way to improve or promote a new ecosystem around the Elixir documentation, and at some point we can bring those improvements back into ExDoc itself.

Take for example http://toolbox.elixir.pm/ which offer a categorized catalog of Hex packages for Elixir and the Erlang ecosystem.

So, this a list of approaches that we can follow:

First option:

1. Merge this change into `master`
2. Wait for somebody to complain about the failure in Chrome with the `file` protocol
3. Try to fix the bug mentioned in 2
4. Provide a JSON formatter with ALL the documentation in this notation.

Second option:

1. Find a way to make this work in Chrome without the `--allow-file-access-from-files` parameter. I haven't tried, but I think this is feasible because we can chain the `.fail()` callback of the `$.getJSON` method and then inside we can use the File API from Chrome, FileReader or something similar.
2. Merge this change into `master`
3. Provide a JSON formatter with ALL the documentation in this notation.

Third option:

1. Provide an `ex_doc server` (with an optional `--reload`) to see a preview as we document our code.
2. Merge this change into master
3. Provide a JSON formatter with ALL the documentation in this notation.

Fourth option:

1. Reject this PR, discard the performance gain for the HTTP protocol.
2. Provide a JSON formatter with ALL the documentation in this notation.

What do you think? /cc @josevalim @ericmj

**Comment by josevalim** [comment]
> I know that you're afraid of making public this object as JSON, or you're afraid about the maintenance issues after releasing this, I know that. But IMHO the good thing is that ExDoc is pre-1.0. 

But the plan is to reach 1.0 rather sooner than later! Considering that, it makes no sense to add a feature we may not want to support forever.

To me, any option that makes docs no longer work offline on some browsers should be discarded, specially given the plans for downloading hexdocs locally. Adding a server is a ridiculous amount of effort for something we already have today. I doubt the gain of using JSON is big enough to justify any of those changes and again, that is without taking into account the current JSON document should not be made public.

**Comment by josevalim** [comment]
If we want to make this functionality available, we should have a separate formatter and have a way of running multiple formatters or something of sorts. I would also like a discussion of what format makes more sense to export the docs. The current format worries about things like IDs and not necessarily in the best way to be consumed by an API.

**Pull request closed without merging**
