### PR TITLE
Ignore escript in .gitignore

### PR DESCRIPTION
**Pull request by RobertDober**
As you are aware I need to build the escript in order to generate the docs for Earmark, while doing so I get a _dirty_ repo, maybe you want to merge this humble PR in order to avoid this?

Thx in advance

### CODE REVIEW

**Comment by josevalim** [comment]
Btw, you can automate the process like this:

https://github.com/plataformatec/nimble_parsec/blob/master/mix.exs#L31-L43

All you need is `mix escript.install hex ex_doc`.

**Comment by josevalim** [comment]
Btw, you can automate the process like this:

https://github.com/plataformatec/nimble_parsec/blob/master/mix.exs#L31-L43

All you need is `mix escript.install hex ex_doc`.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by RobertDober** [comment]
@josevalim muito obrigado for the better way to build the docs!

**Pull request merged**
