### PR TITLE
Group functions based on metadata

### PR DESCRIPTION
**Pull request by lackac**
Related to #876.

- [x] initial documentation for gathering feedback
- [x] add `:groups_for_functions` to configuration
- [x] write tests
- [x] collect functions into groups in Retriever
- [x] update templates and JS
- [x] implement Guards group as a default grouping

### CODE REVIEW

**Comment by josevalim** [comment]
@lackac beautiful. :+1:

**Comment by lackac** [comment]
I was thinking about dogfooding with ExDoc, but since no modules have an abundance of functions it doesn't make much sense to start breaking them into groups.

Instead I would love to get feedback from library authors that might use this feature. I'm going to look into grouping functions in Flow. In Elixir I think `Kernel`, `Enum`, `Stream`, `String`, `File`, and `IO.ANSI` would benefit most from grouping. Any takers? :)

@benwilson512 could you try this on `ExAws.S3`?

**Comment by josevalim** [comment]
@lackac for Elixir, I would go easy and just start with Kernel so far. People have complained about grouping in the past, that makes it harder to find functions since we lose the alphabetical ordering. I agree on `Flow` though! :+1:

**Comment by lackac** [comment]
There's a catch with the current implementation that I haven't made clear. It allows a function to be put into multiple groups. The rules are currently the following:

1. if a function is in any group other than the default "Functions" group, then it won't be put into "Functions"
2. guards will always be in the "Guards" group and optionally in other groups as well, but never in "Functions"
3. all functions without any specific grouping will be grouped into "Functions"
4. since a function can appear in multiple groups it's possible that we violate the uniqueness of html ids in the document. I'm not too worried about this since the browsers handle it well, but would be nice to find a solution to this. In any case there will be an extra id generated for custom groups in order to make the sidebar linking work.

**Comment by josevalim** [comment]
@lackac to avoid the chance of conflicts, I would prefer if we uniquely identify them for now. Otherwise it feels like a tag system, which is something we could add, but maybe out of scope for what we are doing. Thoughts?

**Comment by lackac** [comment]
@josevalim you mean a function could only belong to a single group? That would simplify some decisions. If that's what you want I can make that clear in the docs and make the necessary changes today.

**Comment by josevalim** [comment]
@lackac yes, single group for now. We will say the first matching group is the one that sticks (so they are order dependent). If none is found, it defaults to functions.

**Comment by lackac** [comment]
@josevalim last question: would you put "Guards" in front of custom groups or just before "Functions"? This matters if we only allow a function to appear in a single group.

I'm leaning towards giving custom groups higher priority. ie. if a guard functions is put into a custom group it should only appear there and not in "Guards". This behaviour is then similar to the default "Functions" group.

**Comment by josevalim** [comment]
@lackac The configuration is a keyword list, right? We can keep the same order as in the keyword list. Functions always come last. What do you think?

**Comment by lackac** [comment]
@josevalim that's right, but ExUnit adds an extra default item to that keyword list: `[Guards: & &1[:guard] == true]`. Should this be prepended or appended to the list that comes from configuration?

**Comment by josevalim** [comment]
We won't have a "Guards" default. Elixir will have to add it and other packages will have to add that too if they want it.

**Comment by lackac** [comment]
@josevalim I apologise if I didn't make it clear, but I consider this complete and it can now be reviewed/merged.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
