### PR TITLE
Add a max-width property to img tags

### PR DESCRIPTION
**Pull request by whatyouhide**
This way `` tags don't go far over the right margin of the page, like here:

screen shot 2015-10-28 at 17 12 24

What does the ex_doc team thinks of this? Btw as far as I can tell (I'm not the best you'll find at CSS) this is what GitHub does in their READMEs.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Good idea, do you have a link to a documentation where this is an issue currently?

**Comment by whatyouhide** [comment]
@Dignifiedquire nope, it was causing them for a documentation I was generating but that I still don't publish on hexdocs. But to reproduce you can just take any big-ish image and shove it into a markdown file, that's pretty much what I did :)

**Comment by milmazz** [comment]
@whatyouhide Could you please also provide the bundled CSS file?. You can find more info about this process [here](https://github.com/elixir-lang/ex_doc/tree/master/assets)

**Comment by whatyouhide** [comment]
@milmazz oops, sorry :) `push --force`'d the CSS file, let me know how it looks :).

**Comment by eksperimental** [comment]
@whatyouhide I think you will have to rebase to the latest master, since there's a merge conflict

**Comment by whatyouhide** [comment]
@eksperimental whoops, forgot to do that :) Sorry today my brain is being stupid. `push --force`'d again!

**Comment by milmazz** [comment]
@whatyouhide Thanks!, your change now is in `master`

**Pull request closed without merging**
