### PR TITLE
Normalize CSS class names

### PR DESCRIPTION
**Pull request by milmazz**
Adjust the names of our CSS classes. This take in consideration [one suggestion](https://github.com/elixir-lang/ex_doc/issues/275#issuecomment-130451236) made by @eksperimental

@eksperimental @Dignifiedquire Could you please review this?

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
:+1:

**Comment by eksperimental** [comment]
any reason to leave full_list as such?

**Comment by Dignifiedquire** [comment]
I think the idea to just change classnames in this PR.

**Comment by eksperimental** [comment]
sorry i overlooked the title. I will install this branch and give you an input @milmazz  soon.
@Dignifiedquire can you jump on irc, so you can help me with that? thanks

**Comment by milmazz** [comment]
@eksperimental Feel free to adapt the changes made on this PR in the `new_design`. Just tell us before. @Dignifiedquire will work on the header section in a few minutes. I can push some commits tonight :)

**Pull request merged**
