### PR TITLE
Earmark version bump

### PR DESCRIPTION
**Pull request by RobertDober**
RELEASE NOTE:
# 1.4.5 2020/06/06                                                                                                                                                      
                                                                                                                                                                        
This is mostly a bugfix release, as there were edge cases that resulted in                                                                                              
Earmark crashing, notably                                                                                                                                               
                                                                                                                                                                        
  - Bare IAL                                                                                                                                                            
  - unquoted attributes in html tags                                                                                                                                    
                                                                                                                                                                        
Also autolinks (GFM extension) delivered incorrect URLS where parenthesis were involved,                                                                                
for better GFM compatibility we therefore                                                                                                                               
                                                                                                                                                                        
  - Fixed broken parenthesis links (99% of all cases)                                                                                                                   
  - introduced the same URL encoding/decoding in links and link names of autolinks as GFM does                                                                          
                                                                                                                                                                        
And last but not least all numeric options in the CLI can now be written with                                                                                           
underlines for readability.                                                                                                                                             
                                                                                                                                                                        
- [343-error-parsing-unquoted-atts](https://github.com/pragdave/earmark/issues/343)                                                                                     
                                                                                                                                                                        
- [342 parens in pure links](https://github.com/pragdave/earmark/issues/342)                                                                                            
                                                                                                                                                                        
- [340 IAL might cause error](https://github.com/pragdave/earmark/issues/340)                                                                                           
                                                                                                                                                                        
- [339 Typos fix](ihttps://github.com/pragdave/earmark/pull/339)                                                                                                        
    Kudos to [Ondrej Pinka](https://github.com/onpikono)                                                                                                                
                                                                                                                                                                        
- [336 Smartypants: Convert three hyphens to em dash](https://github.com/pragdave/earmark/pull/336)                                                                     
    Kudos to [Jony Stoten](https://github.com/jonnystoten)                                                                                                              
                                                                                                                                                                        
- [324 Fix AST for links with nested elements](https://github.com/pragdave/earmark/pull/324)                                                                            
    Kudos to [Wojtek Mach](https://github.com/wojtekmach)                                                                                                               
                                                                                                                                                                        
- [320 Nested Blockquotes](https://github.com/pragdave/earmark/issues/320)                                                                                              
                                                                                                                                                                        
# 1.4.4 2020/05/01                                                                                                                                                      
                                                                                                                                                                        
- [338  Deprecation warnings in mixfile removed](https://github.com/pragdave/earmark/issues/338)

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thank you for the PR!

On ExDoc, we already have version requirement: `{:earmark, "~> 1.4.0"}`, hence the conflict. I tried updating it locally and got two failures:

```
  1) test to_ast/1 comments (ExDoc.Markdown.EarmarkTest)
     test/ex_doc/markdown/earmark_test.exs:19
     ** (FunctionClauseError) no function clause matching in ExDoc.Markdown.Earmark.fixup/1

     The following arguments were given to ExDoc.Markdown.Earmark.fixup/1:

         # 1
         {:comment, [" INCLUDE "]}

     Attempted function clauses (showing 6 out of 6):

         defp fixup(list) when is_list(list)
         defp fixup(binary) when is_binary(binary)
         defp fixup({tag, attrs, ast}) when is_binary(tag)
         defp fixup({tag, attrs, ast, _meta}) when is_binary(tag)
         defp fixup({_, _, _})
         defp fixup({_, _, _, _})

     code: assert Markdown.to_ast("<!-- INCLUDE -->", []) == []
     stacktrace:
       (ex_doc 0.22.1) lib/ex_doc/markdown/earmark.ex:58: ExDoc.Markdown.Earmark.fixup/1
       (ex_doc 0.22.1) lib/ex_doc/markdown/earmark.ex:84: ExDoc.Markdown.Earmark.fixup_list/2
       test/ex_doc/markdown/earmark_test.exs:20: (test)

.......................

  2) test synopsis should not end have trailing periods or semicolons (ExDoc.Formatter.HTML.TemplatesTest)
     test/ex_doc/formatter/html/templates_test.exs:138
     Assertion with == failed
     code:  assert Templates.synopsis(Earmark.as_html!(doc1)) == "<p>Summaries should not be displayed with trailing semicolons </p>"
     left:  "<p>\n  Summaries should not be displayed with trailing semicolons :\n</p>"
     right: "<p>Summaries should not be displayed with trailing semicolons </p>"
     stacktrace:
       test/ex_doc/formatter/html/templates_test.exs:151: (test)
```

We can easily fix the 1st failure by adding a catch-all clause. Not sure about the 2nd one.

**Comment by wojtekmach** [comment]
Please also run `mix deps.get`, so our `mix.lock` is updated which would make CI run it with the correct version.

**Comment by RobertDober** [comment]
ok sorry about that, I'll have a look at it next weekend

**Comment by RobertDober** [comment]
but my feeling is that I should also implement the new AST format so that we can that get done in one attempt

**Comment by josevalim** [comment]
Moving to the new format sounds like a good idea. :)

**Comment by wojtekmach** [comment]
I took a stab at fixing the remaining issues so closing in favour of #1188. Thanks @RobertDober!

**Pull request closed without merging**
