### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by eksperimental**
Closes https://github.com/elixir-lang/ex_doc/issues/413

### CODE REVIEW

**Comment by eksperimental** [comment]
added: 
+ Font Awesome
+ Tomorrow theme for Highlight.js
+ webpack
+ loadsh

removed:
- github.com style for highlight.js

**Comment by eksperimental** [comment]
added: 
+ ExDoc theme, Designed by @Dignifiedquire

**Comment by josevalim** [comment]
> ExDoc theme, Designed by @Dignifiedquire

That's an attribution. It isn't a license. The license is the same as ExDoc I think?

**Comment by Dignifiedquire** [comment]
Yes

**Comment by eksperimental** [comment]
updated

**Pull request merged**
