### PR TITLE
WIP: search preview

### PR DESCRIPTION
**Pull request by ThaddeusJiang**
Sorry, It is still work in progress.

- [x]  Fix the left and right arrow navigation. The right arrow should expand, and the left arrow should close, whereas currently they both just toggle

CleanShot 2024-04-04 at 23 04 50

- [x]  The buttons displayed doesn't do anything on click

CleanShot 2024-04-05 at 14 14 36

- [ ]  Use postMessage. The iframe should start as hidden and we should only show the iframe once it uses postMessage. The postMessage should include the content height, so we can render the maximum iframe height accordingly

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @ThaddeusJiang! I changed your branch to merge against search-preview. Let me know when this is ready to merge. :)

**Comment by ThaddeusJiang** [comment]
> Let me know when this is ready to merge. :)

@josevalim ok, I will continue.

**Comment by josevalim** [comment]
@ThaddeusJiang we don't need to tackle everything in one PR. So I will merge the functionaltiy for now and the iframe can be in a follow up one. :)

**Comment by josevalim** [comment]
I have merged this locally and I will push soon! :green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request closed without merging**
