### PR TITLE
Replace css shadow border link underline hack with text-decoration-skip: ink

### PR DESCRIPTION
**Pull request by LostKobrakai**
Regarding https://github.com/elixir-lang/ex_doc/issues/796

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @LostKobrakai . There are two new files in this commit that i think should not be here? epub.css and app.css? Did you build assets with the --type production flag?

**Comment by LostKobrakai** [comment]
I did a `gulp --type production` by accident, maybe it's those.

**Comment by LostKobrakai** [comment]
I've updated the branch without those two files

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
