### PR TITLE
WIP: Name args in Autolink.default_text/4 helper

### PR DESCRIPTION
**Pull request by eksperimental**
WIP because I don't know what name to choose, 
the first argument is prefix, but `p` in `pmfa` stands for prefix as well.

### CODE REVIEW

**Comment by josevalim** [comment]
One is a module prefix (default_text) and the one in pmfa is a link prefix.

**Comment by eksperimental** [comment]
I will name it module_prefix then

**Comment by josevalim** [comment]
Ping! :)

**Comment by eksperimental** [comment]
Totally forgot about this one.
Please have a look again

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
