### PR TITLE
Remove unused fonts from font list

### PR DESCRIPTION
**Pull request by joshprice**
- Switch base h2 to use font-weight 700
- Use font-weight 700 instead of 600 and 800
- Remove duplicate font-weight specification

Addresses #579

### CODE REVIEW

**Comment by antipax** [comment]
lgtm 👍

**Comment by josevalim** [comment]
Great job @joshprice! Let's wait for @dignifiedquire to confirm and then we can ship it. During the night we will also build a new version from the docs and we will be able to see if it implies any difference in practice.

**Comment by eksperimental** [comment]
nice!

**Comment by dignifiedquire** [comment]
Thanks LGTM

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by joshprice** [comment]
Thanks @antipax @josevalim @eksperimental @dignifiedquire. I've only done limited testing on my own machine across a couple of Elixir core modules and everything seemed to look OK to me, but if everyone could keep their eyes out for any potential issues around those fonts once the docs are rebuilt that'd be awesome.

**Pull request merged**
