### PR TITLE
update dependency

### PR DESCRIPTION
**Pull request by tmbb**
Propagate the [awesome](https://github.com/tmbb/makeup_elixir/pull/2#issuecomment-404195559) into ex_doc.

### CODE REVIEW

**Comment by tmbb** [comment]
I have no idea why the build is failing.

**Comment by josevalim** [comment]
> I have no idea why the build is failing.

There is no v1.7 on Travis yet. :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by tmbb** [comment]
A question: does ex_doc now require 1.7? Why?

**Comment by wojtekmach** [comment]
@tmbb ex_doc now uses `Code.fetch_docs/1`, part of EEP 48 effort, which is available in 1.7+.

**Comment by josevalim** [comment]
Yeah, the deprecated notices, since annotations and the new features only work because we are on 1.7+. I am hoping the chunk changes, syntax highlighting and the search effort will finally bring us to 1.0. :)

**Pull request merged**
