### PR TITLE
Fix anchor links when node type is callback/type

### LINKED ISSUE #307: Deep links from sidebar are broken
Ex: http://hexdocs.pm/ecto/Ecto.Repo.html#update_all/3 is what you get when you click the sidebar
but http://hexdocs.pm/ecto/Ecto.Repo.html#c:update_all/3 is what it should be.

### PR DESCRIPTION
**Pull request by milmazz**
This commit fix the anchor links (in the sidebar area) when the node type is: `defmacrocallback`, `callback` or `type`.

As a side note, I think that we can do it better, I don't like the current implementation of the `sidebar_items_*_template.eex` templates, what do you think? any suggestion is more than welcome.

Closes #307

### CODE REVIEW

**Comment by josevalim** [comment]
@milmazz moving to another template function seems to be too much. It feels like those functions generating JSON would be better written in pure Elixir than using `.eex` files. Their contents are mostly code instead of being mostly text.

**Comment by milmazz** [comment]
@josevalim Better? Let me know if you have another tip :smiley:

**Comment by josevalim** [comment]
Yes, I think so, way less indirection.  :shipit:

**Comment by Dignifiedquire** [comment]
@milmazz why the addition of th eslintrc file?

**Comment by milmazz** [comment]
@Dignifiedquire That was trying to fix the error reported by Travis-CI after the ESLint check. What do you suggest to do in this case?

**Comment by Dignifiedquire** [comment]
@milmazz I see, but you don't need to create a new config, just move the one we have in `assets` https://github.com/elixir-lang/ex_doc/blob/master/assets/.eslintrc to the top level of the repo, that way all js files are covered.

**Comment by milmazz** [comment]
@Dignifiedquire I'll fix this problem in another PR, even moving the `.eslintrc` file to the root directory is not enough, could be an issue with Travis-CI? I made some tests in other VM and everything is working OK.

**Comment by Dignifiedquire** [comment]
@milmazz master looks good now, all fixed?

**Comment by milmazz** [comment]
Yes sir :)

**Pull request merged**
