### PR TITLE
Highlight.js improvements

### PR DESCRIPTION
**Pull request by milmazz**
This PR include the latest release of [highlight.js](https://highlightjs.org/) (v8.6) and some improvements in the JavaScript code that allow the auto-detection to Elixir and Bash blocks.

Please note that the original file `elixir.css` was renamed to `github.css` to keep the same name as the source (taken from [highlight.js](https://github.com/isagalaev/highlight.js)) and the few changes (background and border of the `<pre>` tags) were implemented on `highlight-custom.css`. This change will facilite to keep track of the `github.css` changes.

Last but not least, this PR is based on the ideas discussed on #150 by @Dignifiedquire

### CODE REVIEW

**Comment by josevalim** [comment]
I want to avoid generating many assets. Can we add the .hljs to the existing `style.css` with a comment and keep the github.css one as elixir.css? The reason is that github.css is not very clear as a name while elixir.css is. :) Thank you@

**Comment by eksperimental** [comment]
I cannot look at this commit now, but i would discourage the use of the autodetec ion feature.of highlight.js, as we have done in the past and it does a poor job a detcting (probably too hard of a job to solve), so that would recommend this rule, resolve to elixir unless otherwise specified in the code block

**Comment by Dignifiedquire** [comment]
> resolve to elixir unless otherwise specified in the code block

The problem with that is that you can only specify the language if you enable fenced code blocks, which @josevalim [doesn't want](https://github.com/elixir-lang/ex_doc/pull/211#issuecomment-104168759)

**Comment by ericmj** [comment]
I want to confirm that we cannot use autodetect, it brings a lot more issues than the benefits.

**Comment by milmazz** [comment]
@ericmj Have you confirmed that we cannot use the auto-detection feature from `highlight.js`?

After  #211, which offer support for *fenced code blocks*,  can we assume that the auto-detection feature from `highlight.js` is not require in our case? 

It's easy to disable this feature:

```javascript
// Setup Highlight.js
hljs.configure({
  tabReplace: '    ', // 4 spaces
  languages: [] // disable auto-detect
});
```

What do you think? /cc @josevalim @Dignifiedquire

**Comment by josevalim** [comment]
Yes, we are definitely not using autodetect from highlight.js even more now with upcoming support for fenced blocks.

**Comment by milmazz** [comment]
@josevalim Wow, that was fast! working on it! :thumbsup:

**Comment by Dignifiedquire** [comment]
sounds good to me :)

**Comment by milmazz** [comment]
@ericmj @josevalim Do I need to do something else to complete this Pull Request? are you too busy right now to review this?

I'm not in a hurry, I'm just curious, that's all! :+1:

**Comment by ericmj** [comment]
LGTM. @josevalim we can merge and check the nightly docs build.

**Comment by milmazz** [comment]
@josevalim Ping.

**Pull request merged**
