### PR TITLE
Ci for 1.18

### PR DESCRIPTION
**Pull request by RobertDober**
same PR as before but with updated CI

### CODE REVIEW

**Comment by RobertDober** [comment]
seems that was not really productive, sorry

**Comment by josevalim** [comment]
HI @RobertDober, it looks good to me. What is your concern? :)

**Comment by RobertDober** [comment]
> HI @RobertDober, it looks good to me. What is your concern? :)

the failing test for 1.18

**Comment by josevalim** [comment]
I see. that's a formatter thing.i will take a look at it later, thanks for pointing it out!

**Comment by RobertDober** [comment]
com prazer

Feliz Natal o José

**Pull request closed without merging**
