### PR TITLE
[WIP] New design for ExDoc

### LINKED ISSUE #150: Design Refresh
I really enjoy the integration of elixir, with the automated documentation generator but felt myself wishing for a more up to date design of this documentation. So I opened up Photoshop and started designing. This is what I've come up with so far, I would love some feedback on this before moving onto the details and implementation.

A few things should be noted, this design expects the removal of iframes. I think that would be good improvement, but if there are strong reasons for keeping the iframe layout I could work around that.

redesign01

### PR DESCRIPTION
**Pull request by milmazz**
This PR is an attempt to continue with @Dignifiedquire's work and also try to fix #150

This stage includes a manual merge from @Dignifiedquire's [new-design](https://github.com/Dignifiedquire/ex_doc/tree/new-design) branch. However, the file `style.css` needs some tweaks and more work needs to be done (e.g. Change all the Glyphicons references to Font Awesome or include a better support for assistive technologies #235)

Also, I want to include a footer saying that the site was built using `ExDoc` or something like that.

Any feedback is more than welcome.

### CODE REVIEW

**Comment by ericmj** [comment]
I feel like we are doing too many changes with ex_doc for a single release. We should fix all issues in master, release it, and then start working on the new design.

**Comment by josevalim** [comment]
I agree with @ericmj. We haven't released in a while. @milmazz can we do a plan to get the current version out and then work on the new design? :)

**Comment by Dignifiedquire** [comment]
@milmazz I'll update the mockup to include a footer, any thoughts on what more details should be in there, something like `Generated by ExDoc v1.3`

**Comment by milmazz** [comment]
@josevalim @ericmj Ok, I'll put this on hold. I'll work on fix bugs and create the plan that you suggested to get the release done.

@Dignifiedquire Sure, go ahead.

**Comment by josevalim** [comment]
@milmazz I think we are all done for a new release, the bugs listed here are all fixed. :) Let's just wait a day or two and do a new release. Then we can get started on this!!! :D

**Comment by milmazz** [comment]
@josevalim Wow, you're on fire!, you solve all the pending issues :astonished: I need to catch up with your recent commits.

Do you want to solve the issues mentioned on #252 for this release? I can start to work on this ticket after office hours.

**Comment by josevalim** [comment]
Now, they are minor issues. I think what we have right now is excellent for a release. :)

**Comment by josevalim** [comment]
@milmazz @eksperimental I have released 0.8.0! Good job everyone! :heart:

Instead of merging the new design into master though, let's create a new branch in ex_doc. We can use it to try out and merge things like brunch/gulp support until we think it is good enough to be part of master.

**Comment by eksperimental** [comment]
yeah.. great job everyone, specially the big changes by @milmazz ;-D

**Comment by milmazz** [comment]
Thanks everyone, you also did a great job for this release.

I'll close this PR and then I'll create a new one to push the design proposal into a new branch as @josevalim suggested.

There are still a lot of things to do, but, in order to focus on the things that the users really need, can we create a roadmap for the next release?, I mean, can we define our goals for the release v0.9?, for example:

* Include a new design
* Include a build system (Brunch/Gulp) to concatenate and reduce the size of our assets. Also this build system must provide a way to check the quality of our JS code (JSLint maybe)
* Include some tests for JS (QUnit is an option, it's used by the jQuery project) to avoid break some the features in the `app.js` file.
* I remember that @eksperimental mentioned that it would be useful to provide another documentation formats (e.g. epub, pdf)

Finally, where is the best place to discuss this kind of things?

**Comment by josevalim** [comment]
We can discuss them here. Open up an issue with those marked as tasks,
similar to how we did to the current "redesign". :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Dignifiedquire** [comment]
Ref #260 added a list that I'm working, on happy to hear feedback :)

**Pull request closed without merging**
