### PR TITLE
make use of the makeup lexer registry

### PR DESCRIPTION
**Pull request by tmbb**
Because I've been too lazy to write new makeup lexers, I haven't actually tested the possibility of using lexers for languages other than Elixir. All current tests pass, of course.

### CODE REVIEW

**Comment by tmbb** [comment]
@josevalim I have no idea why the build fails with OTP 22. It has probably something to do with the `makeup` application not being started properly (it creates the lexer registry on startup), but I don't know why it should be started in previous OTP versions and not when using OTP 22...

**Comment by josevalim** [comment]
@tmbb we run some checks only on latest Elixir/OTP, but it is a general issue. I will work on a fix. :)

**Comment by josevalim** [comment]
@tmbb can you please rebase? Then it should work!

**Comment by josevalim** [comment]
Nevermind, merged manually. Thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request closed without merging**
