### PR TITLE
[assets] Replace font-awesome with a custom bundle

### LINKED ISSUE #410: [assets] Use custom font-awesome built to reduce the bundle size
Ref #402 

* Create the bundle with this tool: https://icomoon.io/

### PR DESCRIPTION
**Pull request by Dignifiedquire**
We now use https://icomoon.io/ to generate a small custom font bundle
instead of relying on the whole set of font-awesome.

Closes #410

### CODE REVIEW

**Comment by josevalim** [comment]
This is awesome! Is it much more compact in size?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Just being curious: will this still do external requests or is it all local
now? I have no idea looking at the code :D

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Dignifiedquire** [comment]
icon fonts are not loaded externally in master and they are not with this pr

**Comment by milmazz** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
Size before: `56kb`
Size after: `4kb`

**Pull request merged**
