### PR TITLE
Add borders to code tags

### PR DESCRIPTION
**Pull request by aphillipo**
I have compiled the assets in production mode too but let me know if you just want the less updates.

### CODE REVIEW

**Comment by aphillipo** [comment]
Fixes #739 ...

**Comment by eksperimental** [comment]
do you have a screenshot? thank you!

**Comment by aphillipo** [comment]
Here you go!

screen shot 2017-06-08 at 15 20 06

screen shot 2017-06-08 at 15 20 17

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
