### PR TITLE
add link to changelog

### PR DESCRIPTION
**Pull request by jlgeering**
direct link from https://hex.pm/packages/ex_doc to changelog

### CODE REVIEW

**Comment by josevalim** [comment]
There is nothing wrong with including a link to the CHANGELOG but we don't have this habit in our projects and, since we include the link to the source, the information can easily found. Thanks @jlgeering!

**Comment by jlgeering** [comment]
@josevalim you are correct, it is just 1 additional click, but it is an annoying one. Damn, why are habits so hard to change ;-)

But maybe there is a better / easier way that I don't know of, to got from the output of mix hex.outdated to the changelog of a package, without having to search for the package on hex.pm? Or would that be a feature request for hex?

**Comment by jlgeering** [comment]
@josevalim and would you also reject a PR to add the changelog as a page to the documentation (extra), like for example https://hexdocs.pm/quantum/changelog.html ?

**Comment by josevalim** [comment]
@jlgeering also note that linking to master will definitely be wrong for most releases. Since pages are not per release, I don't think including the changelog there is a good idea. Including it as part of the docs is definitely a better option. We can try that! :+1:

**Comment by jlgeering** [comment]
well I would tend to disagree on linking to master not being a good thing, as for example https://github.com/elixir-lang/ex_doc/blob/master/CHANGELOG.md actually contains all versions and so is appropriate for all releases ;-)

anyways, created a PR for plan B

**Pull request closed without merging**
