### PR TITLE
[Issue 730] - Improving Search Engine Results - Sidebar links

### PR DESCRIPTION
**Pull request by cryic**
As a potential solution for https://github.com/elixir-lang/ex_doc/issues/730, this adds a check to create same-page anchors if the node is local.

For example, when on https://hexdocs.pm/elixir/Enum.html, the sidebar links under MODULES>Enum>Functions would be:

`<a href="#fetch/2">fetch/2</a>`

vs.

`<a href="Enum.html#fetch/2">fetch/2</a>`

I think this could help the visibility of on-page destinations in search engine's results.

Please let me know your thoughts on refactoring the check into a separate helper. I left it as is to be explicit about the check, however, it is a bit ugly.

### CODE REVIEW

**Comment by eksperimental** [comment]
Do you have any documentation that backs this?

**Comment by cryic** [comment]
Unfortunately, not much at all. Having tried to research this, most discussions were around absolute vs relative urls, and had no discussion about anchor links.

I had thought of this as an actionable difference after comparing against other pages. I think it definitely isn't a 'full' solution, but thought it may help. I can close this if people don't think this would help or add very much.

Thanks for your suggestions in the issue thread!

**Comment by josevalim** [comment]
@cryic shall we change this according to #922? Thank you!

**Comment by cryic** [comment]
@josevalim That sounds good. Time got away from me, but I've gotten a start on #922. For now, I'll close this PR and open a new one when that work is finished.

Thanks @eksperimental for suggesting and writing up the issue.

**Pull request closed without merging**
