### PR TITLE
Align all h2 section headings correctly

### PR DESCRIPTION
**Pull request by joshprice**
Previously this style was only applied to `#moduledoc` h2's.

Also the `left-margin` has been changed to `.3em` to
counteract the `.3em` padding on the anchor tag.

Should fix alignment of the following:

http://elixir-lang.org/docs/master/mix/Mix.html#module-mix-project
http://elixir-lang.org/docs/master/elixir/Kernel.html#summary (Functions header)
http://elixir-lang.org/docs/master/elixir/Kernel.html#!/1-examples

### CODE REVIEW

**Comment by joshprice** [comment]
Looks like there might be some issues with the alignment for http://elixir-lang.org/docs/master/mix/Mix.html#module-mix-project.

Investigating, please don't merge yet.

**Comment by josevalim** [comment]
Ready to merge? :)

**Comment by joshprice** [comment]
Yes should be good to go. Think I've aligned everything but worth being on the look out for any exceptions...

**Comment by dignifiedquire** [comment]
@joshprice could you add some before/after screenshots, I'm having a hard time seeing exactly what this fixes. Thanks you :)

**Comment by josevalim** [comment]
@dignifiedquire if you [open this page](http://elixir-lang.org/docs/master/mix/Mix.html#module-mix-project), the first h2, which is the "Mix.Project" section, is slightly indented, while none of the other headers are.

**Comment by dignifiedquire** [comment]
Thanks @josevalim I see it now :) 

And thank you @joshprice for fixing :octocat: 

LGTM

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by joshprice** [comment]
Also the h2's in detail sections were slightly outdented (ie http://elixir-lang.org/docs/master/elixir/Kernel.html#!/1-examples).

Thanks everyone!

**Pull request merged**
