### PR TITLE
Remove noindex meta tag

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by eksperimental** [comment]
@ericmj  what is the rationale to have the search engines index a redirect page?

**Comment by ericmj** [comment]
When you go to `hexdocs.pm/PACKAGE` you are internally redirected to `hexdocs.pm/PACKAGE/index.html` on the CDN which ex_doc then redirects to whatever you have configured as your `:main` page. Since `index.html` is not indexed it will not show up in results, which means that if you change your `:main` page the search engine results can show at worst a 404 page or at best an old `:main` page, until they are updated. But if `hexdocs.pm/PACKAGE` showed up in the search results then it will always point to the latest `:main`.

The other potential issue, that is hard to confirm, is that having `noindex` on the page that most people link to can make search rankings worse since most search engines rank based on how many links points to your page. But if they link to a page that is not indexed will it then be included when the ranking is determined?

Because of these potential issues and because `noindex` doesn't seem to provide any value we decided to remove it.

**Comment by eksperimental** [comment]
> When you go to `hexdocs.pm/PACKAGE` you are internally redirected to `hexdocs.pm/PACKAGE/index.html` on the CDN which ex_doc then redirects to whatever you have configured as your `:main` page. Since `index.html` is not indexed it will not show up in results, which means that if you change your `:main` page the search engine results can show at worst a 404 page or at best an old `:main` page, until they are updated. But if `hexdocs.pm/PACKAGE` showed up in the search results then it will always point to the latest `:main`.
> 
> The other potential issue, that is hard to confirm, is that having `noindex` on the page that most people link to can make search rankings worse since most search engines rank based on how many links points to your page. But if they link to a page that is not indexed will it then be included when the ranking is determined?
> 
> Because of these potential issues and because `noindex` doesn't seem to provide any value we decided to remove it.

Thanks A LOT for the clarification @ericmj 
I

**Pull request merged**
