### PR TITLE
Add sourcemaps for JS (fixes #687)

### LINKED ISSUE #687: Provide source maps for JS
When debugging errors like #685 is almost impossible to use the *Developer Tools* and put breakpoints in the `app-*.js` minified version, even with the *pretty print* feature from Chrome or other browsers is difficult to understand the application workflow:

image

One way to do this task a little easier is providing a source map. We should add a new task in our current `gulpfile.js` workflow. wdyt?

### PR DESCRIPTION
**Pull request by milmazz**

### CODE REVIEW

**Comment by josevalim** [comment]
Please check the build. :)

**Comment by milmazz** [comment]
@josevalim It should be ready now...

**Comment by josevalim** [comment]
I am wondering if we should always copy the sourceMaps or should we introduce a --debug flag during generation.

@ericmj does this impact hexdocs in any way?

**Comment by ericmj** [comment]
Nothing more than a few extra bytes stored, I would think, which should be fine.

**Pull request merged**
