### PR TITLE
Fix html escaping in the sidebar entries

### PR DESCRIPTION
**Pull request by davydog187**
Fixes https://github.com/elixir-lang/ex_doc/issues/1283

Screen Shot 2020-10-05 at 10 03 36 AM

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thank you!

**Comment by eksperimental** [comment]
We are going back and forth trying to solve the issue.
Please have a look at https://github.com/elixir-lang/ex_doc/pull/1245, and https://github.com/elixir-lang/ex_doc/commit/959a0206e2f6906450913bedc574ee74351e5f99#diff-d85f51765b385ca15bb7242d5936ac89

and this issue 
https://github.com/elixir-lang/ex_doc/issues/1244

**Comment by eksperimental** [comment]
this PR just reverted a previous commit that solved the issue. Please make sure the other issues don't come back. thanks.

**Comment by davydog187** [comment]
@eksperimental sounds like this needs a complete overhaul then. We're currently sending `{id: "id", anchor: "anchor"}` to the frontend. I suggest we add something like `{id: id, anchor: anchor, text: text}` as we're trying to use id for multiple purposes at the moment.

I know there are plans to redo the sidebar, and we keep making excuses for broken behavior because of it. I would like to participate in these improvements. Is there a working group meeting for documentation?

**Comment by davydog187** [comment]
We should couple this with more comprehensive front-end tests. I'll rethink this PR with both issues in mind.

**Comment by eksperimental** [comment]
> @eksperimental sounds like this needs a complete overhaul then. We're currently sending `{id: "id", anchor: "anchor"}` to the frontend. I suggest we add something like `{id: id, anchor: anchor, text: text}` as we're trying to use id for multiple purposes at the moment.
I thought of your suggestion when I worked on the linked PR above, but I thought I covered all the fronts, so I didn't do it. I think We should give it a go and add (I am not a JS person) Javascript tests for every reported issue.

> I know there are plans to redo the sidebar, and we keep making excuses for broken behavior because of it. I would like to participate in these improvements. Is there a working group meeting for documentation?
There is an erlang foundation working group for the documentation, but ExDoc is out of its scope. As far as I know there is no group meeting for documentation related to ExDoc

**Comment by wojtekmach** [comment]
@eksperimental are you saying this bug was already fixed and we've just broken it again?

before @davydog187's PR, on master with the following changes:

```diff
diff --git a/README.md b/README.md
index 40a19f8..14a151d 100644
--- a/README.md
+++ b/README.md
@@ -9,6 +9,8 @@ To learn about how to document your projects, see [Elixir's writing documentatio

 To see all supported options, see the documentation for [mix docs](https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html)

+## Foo & Bar
+
 ## Features

 ExDoc ships with many features:
```

and after running `mix build` I could see the bug. Could you please verify?

I just double-checked and before this PR I was seeing the bug and after it I wasn't.

**Comment by eksperimental** [comment]
> @eksperimental are you saying this bug was already fixed and we've just broken it again?

What I am saying is that if you look at the history of this file, it reverts the changes from 2 commits behind which tried to solve a similiar issue (I wrote that commit myself), so by the look of it, is that it is fixing this bug but it could bring the other one, but i haven't looked at it. I was writting my comment before this PR was merged.

**Comment by eksperimental** [comment]
@wojtekmach  Sorry, I haven't run it with this new commit yet. I will later and report back

**Comment by wojtekmach** [comment]
the other bug was the following, right?

image

I just built Elixir docs with ExDoc master (which contains this PR) and it works correctly:

image

image

if you could test it locally I'd appreciate it. You're right that we've been going back'n'forth in that js file so if, assuming we finally got it right, there's still opportunity to clean it up, that'd be appreciated too.

Btw,  thanks for keeping an eye on it!

**Comment by eksperimental** [comment]
@wojtekmach It does work as expected! thank you @davydog187 
We should only add the JavasScript tests then

**Comment by davydog187** [comment]
@eksperimental I will plan to add some tests in the JS land, i'll create an issue to track

**Pull request merged**
