### PR TITLE
Handle --proglang string

### PR DESCRIPTION
**Pull request by erszcz**
Hey!
I was just trying the current master on some Erlang projects and found this tiny issue. Works like a charm with this fix 🎉

### CODE REVIEW

**Comment by josevalim** [comment]
Nice, we should probably normalize it up higher though! Maybe on the CLI module?

**Comment by wojtekmach** [comment]
Since both ExDoc.CLI and Mix.Tasks.Docs parse options perhaps it's better to put the normalisation into the ExDoc.build_config/3 which both of them use under the hood? I was thinking about:

```diff
diff --git a/lib/ex_doc.ex b/lib/ex_doc.ex
index 0a1afcd3..8715ea62 100644
--- a/lib/ex_doc.ex
+++ b/lib/ex_doc.ex
@@ -46,7 +46,7 @@ defmodule ExDoc do
       main: options[:main],
       output: normalize_output(output),
       homepage_url: options[:homepage_url],
-      proglang: proglang,
+      proglang: normalize_proglang(proglang),
       source_root: options[:source_root] || File.cwd!(),
       source_url_pattern: source_url_pattern,
       nest_modules_by_prefix: normalize_nest_modules_by_prefix(nest_modules_by_prefix),
@@ -85,6 +85,18 @@ defmodule ExDoc do
     String.trim_trailing(output, "/")
   end

+  defp normalize_proglang(binary) when is_binary(binary) do
+    binary |> String.to_atom() |> normalize_proglang()
+  end
+
+  defp normalize_proglang(proglang) when proglang in [:elixir, :erlang] do
+    proglang
+  end
+
+  defp normalize_proglang(proglang) do
+    raise ArgumentError, "#{inspect(proglang)} is not supported"
+  end
+
   defp normalize_groups_for_modules(groups_for_modules) do
     default_groups = [Deprecated: &deprecated?/1, Exceptions: &exception?/1]
```

wdyt?

**Comment by erszcz** [comment]
Looks and works great! I've force pushed your patch, @wojtekmach.

**Comment by wojtekmach** [comment]
Thanks!

**Pull request merged**
