### PR TITLE
Add atom module name to list for doc generation

### PR DESCRIPTION
**Pull request by allyraza**
issue #514

### CODE REVIEW

**Comment by ericmj** [comment]
Can you check if this works when you have all erlang files in your mix project?

**Comment by allyraza** [comment]
I did run a test with a erlang module, Elixir module atom as name and a normal elixir module with ecto as dep and it worked

**Comment by josevalim** [comment]
Sorry but I don't see how this patch would work. If you load all modules, this line will later fail for Erlang modules: https://github.com/elixirdrops/ex_doc/blob/issue-514/lib/ex_doc/retriever.ex#L99

**Comment by allyraza** [comment]
@josevalim I setup a test project with the latest changes (https://github.com/elixirdrops/unicorn) and seems to work

**Comment by ericmj** [comment]
@allyraza Erlang files need to be put in the src/ directory.

**Comment by allyraza** [comment]
is it possible to detect that a given module is erlang module

**Comment by ericmj** [comment]
You can check if it has the `__info__/1` function, but I have suggested that previously and it was not used.

**Comment by allyraza** [comment]
okay this should do it

**Comment by lpil** [comment]
What's the status here?

**Comment by milmazz** [comment]
@allyraza Are you still working on this? Thanks!

**Comment by allyraza** [comment]
@milmazz this has been completed long time ago

**Comment by josevalim** [comment]
This has been merged on master, thank you! :heart:

**Pull request merged**
