### PR TITLE
Make function signature be an H1 element

### LINKED ISSUE #923: Restructure HTML
Originally posted here: https://github.com/elixir-lang/ex_doc/issues/730#issuecomment-433669048

I have noticed a big semantical mistake in the HTML structure,
the name of the function should be a HEADER element, `<h2>` to be precise.
As of now, It is just a span, and then if there is a section inside this functions, this receives `<h2>`.
We should use `<h2>` for the function name, and them push up +1 all the headers within the function.

### PR DESCRIPTION
**Pull request by eksperimental**
Closes #923

### CODE REVIEW

**Comment by eksperimental** [comment]
Oops. I will when i get to the computer

**Comment by eksperimental** [comment]
Have a look now

**Comment by josevalim** [comment]
CI is still failing, can you please investigate @eksperimental? Thanks!

**Comment by eksperimental** [comment]
Sorry, totatlly forgot to run `mix test`

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
