### PR TITLE
Display search results in the content area.

### PR DESCRIPTION
**Pull request by Dignifiedquire**
cc @milmazz

### CODE REVIEW

**Comment by milmazz** [comment]
@Dignifiedquire Wow, this is amazing, here a couple of suggestions:

* Provide an alternative way to start the search process, right now the user must press the `ENTER` key
* If you try to find something like `File.ls` does not work, I think must show the following functions: `ls/1`, `ls!/1`, `lstat/1` and `lstat!/1`.
* Provide a way to *close* the search result and go back to the previous page.

**Comment by milmazz** [comment]
@Dignifiedquire Ping?

**Comment by Dignifiedquire** [comment]
will fix later today

**Comment by Dignifiedquire** [comment]
Fixed everything except the search in nested functions. Was that working before?

**Comment by milmazz** [comment]
@Dignifiedquire are you referring to this?

> If you try to find something like `File.ls` does not work, I think must show the following functions: `ls/1`, `ls!/1`, `lstat/1` and `lstat!/1`.

Yes.

**Comment by Dignifiedquire** [comment]
@milmazz all done :) let's get this shipped :ship:

**Comment by milmazz** [comment]
@Dignifiedquire Awesome!

**Pull request merged**
