### PR TITLE
Update CSS theme and switch to new makeup_elixir version

### PR DESCRIPTION
**Pull request by tmbb**
This version fixes 2 genuine bugs and 1 smaller issue that makes it play better with the CSS theme.

### CODE REVIEW

**Comment by tmbb** [comment]
Example of the elixir docs rendered with this version: https://tmbb.github.io/exdocs_makedown_demo/api-reference.html

**Comment by josevalim** [comment]
This change is changing JS and that should not be necessary, should it?

Can you run “npm install” and “npm build” and see if they generate the same
CSS? Alternatively, remove the dist/ changes from the PR and I will do that
after merge. Thanks!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tmbb** [comment]
> This change is changing JS and that should not be necessary, should it?

It shouldn't.

But when I reinstall the node deps and build the assets I get the same javascript.

**Comment by tmbb** [comment]
> Alternatively, remove the dist/ changes from the PR and I will do that after merge. Thanks!

I don't understand. Do you want me to remove the generated files so that you can regenerate them?

**Comment by josevalim** [comment]
Ok. Can you just submit the raw changes then? I will investigate the
reproducibility of those builds later.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tmbb** [comment]
> Ok. Can you just submit the raw changes then?

A new repo just for the changes?

**Comment by josevalim** [comment]
No, sorry. I mean a PR only with the markup.css and mix.lock changes. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Oops, and the mix.exs changes too. Maybe we should depend on makeup_elixir
~> 0.8 instead of 0.8.0?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tmbb** [comment]
> No, sorry. I mean a PR only with the markup.css and mix.lock changes. :)

With the old dist/ contents?

**Comment by josevalim** [comment]
Back at the computer, I have done the changes by hand. :) Thanks!

**Comment by tmbb** [comment]
Ok, thanks!

**Comment by tmbb** [comment]
I'm still away from the computer, but could you please update the makeup_elixir version to "~> 0.8"? The new CSS assumes we're using that version (and it has some bug fixes too)

**Comment by josevalim** [comment]
Will do later on but 99% of the users will likely get it anyway.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Pull request closed without merging**
