### PR TITLE
[WIP] New Styles

### PR DESCRIPTION
**Pull request by Dignifiedquire**
- [x] Remove twitter bootstrap
- [x] Cleanup selectors
- [ ] Finish sidebar
- [ ] Content styles

Search will be broken, will be fixed in a separate PR.

Current progress:

screen shot 2015-08-18 at 23 41 50

### CODE REVIEW

**Comment by milmazz** [comment]
@Dignifiedquire Can I rebase again the `new_design` branch to include the latest fixes from `master`?, in a few hours I can work in the new structure for `sidebarNodes`.

**Comment by Dignifiedquire** [comment]
@milmazz sure go ahead

**Comment by Dignifiedquire** [comment]
Current version: 

screen shot 2015-08-21 at 22 39 43

**Comment by Dignifiedquire** [comment]
Some more content styles are done :) 
screen shot 2015-08-22 at 01 21 42

**Comment by josevalim** [comment]
@Dignifiedquire it looks beautiful! I love the function bits (the purple box).

One quick question: because of the function names (the purple box) and code examples (blue box) look similar, at first glance, it is hard to put them apart in a way that the function names stand-out less. Maybe we could make the code one a bit less similar, maybe by simply removing the left-border from the code one or using another border style or using border on another side?

**Comment by josevalim** [comment]
I think removing the left-border from the code one will be enough. It will still be clean but not call so much attention as the function names.

**Comment by Dignifiedquire** [comment]
@josevalim I improved it a bit, let me know what you think

screen shot 2015-08-22 at 12 33 57

**Comment by josevalim** [comment]
@Dignifiedquire I thought about such but I am worried that the bold will take space and things will break for long function names or ones that expect a lot of arguments.

**Comment by josevalim** [comment]
For example this one: http://hexdocs.pm/phoenix/Phoenix.Socket.Transport.html#check_origin/5 (there is a bug in there but it works as an example).

**Comment by Dignifiedquire** [comment]
I've reduced the font size slightly but I think this looks good, given the amount of content:

screen shot 2015-08-22 at 13 07 58

**Comment by josevalim** [comment]
Great! :D



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by milmazz** [comment]
@Dignifiedquire Awesome work!, I'll close this PR because I already execute the `rebase` in `new_design`. Please open a new PR, also, keep in mind that the new JSON structure is already done in #310, I'll wait for your feedback and then I'll merge those changes with `new_design`, after that we can focus on finish all the design elements, then we can focus in the search feature.

**Pull request closed without merging**
