### PR TITLE
Fix the text decoration for links containing code

### LINKED ISSUE #463: Link containing `code` doesn't underline the code area
Link containing `code` doesn't underline the code area. Making it impossible to determine whether its a link to Module/function or not.

http://elixir-lang.org/docs/master/elixir/Code.html
https://github.com/elixir-lang/elixir/blob/8fd3eb5a2cceb2f48244e3cb1fa11a1a71fc9601/lib/elixir/lib/code.ex#L5

ex_doc_code_link_underlined

### PR DESCRIPTION
**Pull request by nscyclone**
This PR should fix #463.
* Before the fix it used to look like this: before;
* `text-decoration` doesn't fix this: underline;
* So I decided to use `border-bottom` instead. Now it will look like this:
  * In day mode: day;
  * In night mode: night.

//cc @eksperimental @dignifiedquire

### CODE REVIEW

**Comment by eksperimental** [comment]
Looks good to me but im unable to test it live. Thanks for looking after this

**Comment by josevalim** [comment]
Ping @dignifiedquire :)

**Comment by dignifiedquire** [comment]
lgtm code and image wise :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
