### PR TITLE
Fix Safari scrolling lag

### PR DESCRIPTION
**Pull request by net**
Removing the JavaScript focus dispatch fixes the Safari scrolling issue (#851). I also removed the `overflow-y: auto` on `.content` to keep the current behavior where main content is immediately keyboard-scrollable.

The downside to this approach is that scrolling up on the sidebar when the sidebar is fully scrolled to the top, or down when it is scrolled to the bottom, will cause the main content to scroll. This can be fixed, but I wanted to see if we were happy with this simpler option.

Tested on the latest Safari and Chrome.

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @net! Given the purpose of this code was precisely to avoid the sidebar scrolling, I wonder what other alternatives we have to solve this issue. I am quite sure that if we remove this behaviour, we will have bug reports asking to add it back. :)

**Comment by OvermindDL1** [comment]
Why aren't both the sidebar and main page their own scrolling contexts?  If the main body doesn't scroll (just 100% all around) then then should be easily optimized by the browsers?

**Comment by mnussbaumer** [comment]
Not sure if this is solved, if not, just chipping in because I ran into this issue on one of my projects, running macOSX 10.13.6 safari 12.0, this is probably a bug in Safari since neither chrome nor ff do this sluggish scroll. In my own case, specifying `will-change: scroll-position;` for my div removed the sluggishness but it doesn't work on the hex pages (and it shouldn't since there's no transparencies nor anything that could be optimised). What does work is removing the `height: 100%` from the `.content` container, if it's a `block` it will always extend to 100% height automatically, and I think work correctly in any situation.

**Comment by net** [comment]
@mnussbaumer Excellent. Would you like to submit a PR?

**Comment by mnussbaumer** [comment]
> @mnussbaumer Excellent. Would you like to submit a PR?

@net since you already worked on the PR and have it ready I'm totally fine if you do that?

**Comment by RudManusachi** [comment]
In my Safari 12.0.1 it scrolls just fine while safari's "scroll view" is in a background of a system and focus is on a different app, such as finder, or even safari's webinspector in separate window
 
<details>
  <summary>I tried to capture it here</summary>

safariscroll2

</details>

**Comment by josevalim** [comment]
Many are reporting the bug no longer exists, so hopefully it is permanently fixed with the Safari update. Let us know if it isn't. Thanks!

**Pull request closed without merging**
