### PR TITLE
Update README version to 0.26

### PR DESCRIPTION
**Pull request by shahryarjb**

### CODE REVIEW

**Comment by josevalim** [comment]
That version will get the latest 0.26, 0.27, and so on. So it is fine to keep it as is and then we don't have to update always!

**Comment by eksperimental** [comment]
@josevalim I am not getting ExDoc updated.

```
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  ...
  ex_doc 0.26.0
  ...
All dependencies are up to date
```

while latest ex_doc released version is `0.27.3` and my deps config in mix.exs is `{:ex_doc, "~> 0.26", only: :dev, runtime: false}`.
What could it be?

**Comment by josevalim** [comment]
It has to be `mix deps.update ex_doc`.

**Comment by eksperimental** [comment]
Jeez, how could I missed that! Thank you

**Pull request closed without merging**
