### PR TITLE
Introduce :private visibility in Refs

### PR DESCRIPTION
**Pull request by eksperimental**
Addresses the issue of warning about private types, which is not tackled in this PR per se.

### CODE REVIEW

**Comment by eksperimental** [comment]
After the other big PR is merged, I would like to introduce the ref of private functions. So we can properly make the distinction and warning between private and undefined.

**Comment by wojtekmach** [comment]
Yeah, I think we can track “private” functions, I think they are rather uncommon so I wouldn’t worry about them too much but I think it makes sense to do it for completeness. Instead of “private” maybe a better name is “hidden”? That’s the term we use in the chunk spec and there is no ambiguity with truly private functions (I.e. defp).

**Comment by eksperimental** [comment]
We are already tracking those hidden functions (declared with doc false). What I mean here is to track truly private functions (`defp`, `defmacrop`), actually this PR does that with `typep`).

**Comment by wojtekmach** [comment]
There is no way to track truly private functions (as they are not visible to the runtime system), is there? :)

**Comment by eksperimental** [comment]
> There is no way to track truly private functions (as they are not visible to the runtime system), is there? :)

I was able to access private function definitions with `:beam_lib.chunks(beam, [:debug_info])`

**Comment by eksperimental** [comment]
I have implemented tracking private macros and functions. Please have a look.
There is one build failing, it looks like OTP 19 was not tracking these functions, unless it is something related to Elixir v1.7.
This would mean that we will have to move to Elixir v1.8 as the minimum Elixir version.

**Comment by josevalim** [comment]
Apparently I commented in the wrong place, so I will do it here again:

This is using many private APIs from Elixir. Code.Typespec, the debug chunk, none of them are public. I also don't believe we should go down this path, it will make things more complex, more expensive, for little to not benefit. Not even Elixir tries to track these when showing private or undefined function warnings. So I am 👎. :)

**Comment by wojtekmach** [comment]
Agreed with @josevalim

**Comment by eksperimental** [comment]
> Apparently I commented in the wrong place, so I will do it here again:
> 
> This is using many private APIs from Elixir. Code.Typespec, the debug chunk, none of them are public. I also don't believe we should go down this path, it will make things more complex, more expensive, for little to not benefit. Not even Elixir tries to track these when showing private or undefined function warnings. So I am -1. :)

darn! I didnt think that debug_info chunk was not public.

**Comment by eksperimental** [comment]
once #1224 I will update this PR with a middle ground solution that doesn't read from a non public API

**Comment by wojtekmach** [comment]
@eksperimental I initially wrote we could support this feature and that it makes sense to do it for completeness but after reading @josevalim comment I agree that it would add little benefit while increasing complexity, so I wouldn't pursue it further either.

**Comment by eksperimental** [comment]
Well, the implementation was done but the time I posted my comment. but yeah.. it adds complexity.

**Pull request closed without merging**
