### PR TITLE
Load font css from https: when required

### PR DESCRIPTION
**Pull request by eksperimental**
originally published in #404

### CODE REVIEW

**Comment by josevalim** [comment]
@eksperimental weren't we using inline css for some other reason?

**Comment by josevalim** [comment]
Because of this: https://github.com/elixir-lang/ex_doc/commit/f87c8f217dbd2862165d204dd4d023a2ca419942

**Comment by eksperimental** [comment]
The blank page issue was an issue with my system configuration. It was just a work around, but it didnt work.

**Comment by ericmj** [comment]
Why is javascript needed to load css? Why isn't `//` enough?

**Comment by josevalim** [comment]
// won't work with file://

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
In which sense? Does it error or just use http?

Also, why not always use https? We are loading from an external CDN that we know supports https.

**Comment by eksperimental** [comment]
@ericmj `//` will cause when loaded from `file://` to call 
`file://fonts.googleapis.com/css?family=Lato:400,300,700,900|Merriweather:300italic,300,700,700italic|Inconsolata:400,700`

my concern calling https when non needed was unnecessary overhead (for encrypting/decypting) and the higher data transfers due to encrypted data.
I have done some tests with wireshark,

its is __http: 217kb__ vs __https: 230kb__
it's only 13kb, which is only 5% of the data transfered via http.

I'll leave it up to you guys.

ex_doc_http_tcpdump

ex_doc_https_tcpdump

**Comment by josevalim** [comment]
That's really cool @eksperimental! 5% is an OK price to pay though, so I think we are good. :)

**Pull request closed without merging**
