### PR TITLE
Add favicon.ico

### LINKED ISSUE #198: Add favicon.ico
Add elixir favicon.ico as the default icon.
and 
`<link rel="shortcut icon" href="/favicon.ico" />`
to the header

So we can validate these files, with html-proofer

### PR DESCRIPTION
**Pull request by milmazz**
Now by default `ExDoc` adds a `favicon.ico`. However, the user can request to include another _favorite icon_ through the option `-i` or `--favicon`.

Fixes #198

### CODE REVIEW

**Comment by ericmj** [comment]
I don't think a default favicon using the elixir logo should be used. The elixir logo should be used by elixir itself, not by any project written in elixir.

**Comment by milmazz** [comment]
@ericmj Agree, do you have a default favicon suggestion?

**Comment by ericmj** [comment]
We can default to no favicon.

**Comment by milmazz** [comment]
@ericmj I prefer to provide a default favicon, why? I think the favicon is a great visual reminder of the Web site identity in the address bar o even in the tabs (the favicon helps a lot when you have a bunch of open tabs in your browser). Not only that, the HTML5 spec says the following:

> In the absence of a link with the icon keyword, for Documents obtained over HTTP or HTTPS, user agents may instead attempt to fetch and use an icon with the absolute URL obtained by resolving the URL "/favicon.ico" against the document's address, as if the page had declared that icon using the icon keyword.

So, if we don't provide a default favicon some user agents will receive an 404 as HTTP status code for that particular request.

**Comment by ericmj** [comment]
If it's a reminder web site identity it is even worse to include a default, if everyone uses the same favicon it's not really helpful to find the identity.

It's up to each website to provide their own favicon if they want to avoid the 404. That's what hexdocs.pm does for example. A default also means that we will always override the hosting website's favicon, API docs are unlikely to be the only resource on a domain.

**Comment by eksperimental** [comment]
I'm more inclined to create a default icon fo ex-doc that can be freely distributed and can act as a placeholder favicon. Something u can look at see its the documentation of an app written en elixir

**Comment by Dignifiedquire** [comment]
> I'm more inclined to create a default icon fo ex-doc that can be freely distributed and can act as a placeholder favicon. Something u can look at see its the documentation of an app written en elixir

Fully agree with that, sounds much better than no favicon as a default.

**Comment by ericmj** [comment]
@eksperimental I don't see anything in the code that overrides the favicon and lets me use the one on my website instead?

**Comment by milmazz** [comment]
@eksperimental @Dignifiedquire I'm agree to create a default favicon for ExDoc, the problem is that I'm neither a graphic designer nor a web designer to offer one. So, can you help me on this?

@ericmj With the `-i` or `--favicon` option you can specify the _path_ of your icon, then, that file will be copy to the root directory of the documentation. Or you're talking about another use case? Please, can you clarify your requirement?

**Comment by eksperimental** [comment]
@ericmj true. We need an option to skip the favicon link tag.

**Comment by ericmj** [comment]
Say that I'm hosting a website foo.com that has a favicon. On the website I host documentation generated by exdoc at foo.com/docs. How do I make it use the favicon in the root without generating the docs with my favicon and duplicating it?

**Comment by eksperimental** [comment]
@milmazz same here. Zero graphic design skills. I think you coupd ask for help in the elixir-lang and elixir-core mailing lists. Im sure someone will or knows someone who is  be able to contribute to the cause

**Comment by josevalim** [comment]
If you want a favicon on your application, all you need to do is to add one at the root. Browsers already have a sensible default for this, we don't need to do anything really. Also it is very easy for someone to  copy the favicon to their docs directory, either manually or by configuring mix.

**Comment by Dignifiedquire** [comment]
How about something like this: 

favicon-ex-doc

**Comment by eksperimental** [comment]
@josevalim but most of the projects won't have a favicon of their own. So I see it as  a good thing to have default icon, like the one provided by @Dignifiedquire  
I think they should opt-out if they want to use their own.

**Pull request closed without merging**
