### PR TITLE
Capitalize search word

### PR DESCRIPTION
**Pull request by gfvcastro**

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks. Is there any guideline or is it a style change?

**Comment by gfvcastro** [comment]
It is a style change. 😄

**Comment by josevalim** [comment]
Ok, so I will wait for others feedback and then we can move forward (or not). :)

**Comment by christhekeele** [comment]
Just looking at the search bar on the top of this page itself, it looks like GitHub went with `Search` over some of the other common options:

- ✅ 
  screen shot 2017-10-03 at 3 37 28 pm
- ❌
  screen shot 2017-10-03 at 3 38 21 pm
- ❌
  screen shot 2017-10-03 at 3 37 50 pm
- ❌
  screen shot 2017-10-03 at 3 38 07 pm

-----

Applied to Elixir's docs, the options look like:

- ❓
  screen shot 2017-10-03 at 3 39 11 pm
- ❓
  screen shot 2017-10-03 at 3 39 28 pm
- ➡️
  screen shot 2017-10-03 at 3 38 51 pm
- ❓
  screen shot 2017-10-03 at 3 39 46 pm

-----

No opinions or horse in this race, just thought presenting the palette of options might help.

**Comment by ericsolomon** [comment]
I'm in favor of Search. Seems to be the most consistent placeholder or button text when looking at other applications that support search functionality.

Though the search bar on https://elixir-lang.org/ is 'Search...'

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
