### PR TITLE
Implement a splashy new design

### LINKED ISSUE #275: New design
## Action Plan

- [x] Sidebar styles
- [x] Content styles
- [x] Add footer
- [x] Only include from bootstrap what we use, rather than bundling all this stuff we don't need
- [ ] Highlight currently selected items in the sidebar modules/sections 
- [ ] Pull fonts not from `templates/fonts` but from `node_modules/font-awesome` instead
- [x] Remove twitter bootstrap (we use too little of it) and replace it with just normalize plus custom layout
- [x] Review mobile layout
- [x] Update search to use the json data instead of markup (PR #322)
- [x] Remove functions from the sidebar list (PR #320)
- [ ] Add nesting level for the first level of modules
- [x] Show search results in the main content area (PR #322)
- ~~Add logo image support~~ (Delayed)
- ~~Pull fonts from google fonts into the repo so full offline usage is possible~~

## Screens

layout02-v4

/cc @Dignifiedquire @milmazz

### PR DESCRIPTION
**Pull request by Dignifiedquire**
@josevalim @milmazz This is it!

Closes #275

### CODE REVIEW

**Comment by milmazz** [comment]
@Dignifiedquire Feel free to push the *Merge pull request* button :)

**Comment by Dignifiedquire** [comment]
@josevalim @milmazz it's done!

**Comment by josevalim** [comment]
I am so excited! :D I will try this out tomorrow and put this on its way for a 0.9.0 release!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by ericmj** [comment]
This is such great work @Dignifiedquire and @milmazz, thank you for all of your hard work. Looking forward to the nightly elixir master docs build so we can all check this out!

**Pull request merged**
