### PR TITLE
Update asset build pipeline

### LINKED ISSUE #873: Update build to use Webpack instead of Gulp
A conversation was started over on phoenixframework/phoenix#2949 about getting this project updated to Webpack. I would love to tackle this. Is the goal to simply replace the current gulp tasks or is there other changes that would like to get mad

### PR DESCRIPTION
**Pull request by gj**
Closes #873 

- Removes Gulp
- Upgrades Webpack, Babel, Mocha, Karma, ESLint, Less, Lodash, and more to the latest version of each

Regarding @josevalim's [comment](https://github.com/elixir-lang/ex_doc/issues/873#issuecomment-405004848), the coupling between Gulp, Webpack, and Karma made it a bit awkward to update Webpack in isolation.

This PR is all about feature parity, with one exception: there's no more equivalent of the `npm run clean` Gulp task that removed build artifacts. I set Webpack up to automatically remove build artifacts before executing a production build, which retains most of the same functionality as before. If a script solution is preferably to manual rimraffing, I can add a little script for the `npm run clean` functionality.

If this PR is accepted, I would like to simplify the test setup in a followup PR. Right now we're loading a full browser environment but then only running unit tests, which seems like a bit of overkill to me.

## `npm audit`
- Before: `found 84 vulnerabilities (36 low, 24 moderate, 23 high, 1 critical)`
- After: `found 2 low severity vulnerabilities`

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @gj, this looks amazing! Three last questions :

1. What about the generated `.js` size? Is it smaller now?

2. I saw that we changed the approach to highlight.js but I am assuming that the end result is the same?

3. Can we move the `.eslint` files at root to inside the `assets` directory?

:heart:

**Comment by gj** [comment]
@josevalim 

1. Before: EPUB CSS `5.45 kB`; EPUB JS `34.18 kB`; HTML CSS `23.12 kB`; HTML JS `218.05 kB`
    After: EPUB CSS `5.53 kB`; EPUB JS `55 kB`; HTML CSS `24.9 kB`; HTML JS `169 kB`
2. Yep, the HTML docs get highlighted just as before. There's no code highlighting in EPUB files before this PR and still no code highlighting in EPUB files after this PR. I plan to take a look at that after this PR goes in.
3. Yep, good idea. Moved everything asset-related into the `assets/` dir except for `package.json` and `package-lock.json` (so that commands can still be run from the project root).

**Comment by josevalim** [comment]
Thanks @gj, it looks good to go. Just one last change: can you please revert decc9e7 and rebuild the assets? The Elixir syntax highlightning is not done with JS, it is done while we generate the docs using the "makeup" tool. It only supports Elixir right now but the plan is to move to it little by little. :)

**Comment by gj** [comment]
@josevalim haha I just noticed that too (in b44eba1a613ee342328833b0e02b214e0869a3ac)

Reverted and the CI is running 😄

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
