### PR TITLE
Decrease size of headings in the detail section

### LINKED ISSUE #419: [Usability] Function headings are not clear
I am having a hard time trying to spot where the functions begin.
I think we need to make clear where a function ends and where a new one starts..
Please, have a look at this screenshot.
ex_doc_fuction_heading

I know where Example Starts,
and the second Example begins.
but to my tired eyes, it looks like **intersperse** belongs to the top Example, when it is sort of the opposite.

WDYGT

### PR DESCRIPTION
**Pull request by milmazz**
With this we make clear where a function ends and where a new one starts. /cc @Dignifiedquire 

## Before

screen shot 2015-11-16 at 6 20 08 pm

## After

screen shot 2015-11-16 at 6 36 54 pm

Fixes #419

### CODE REVIEW

**Comment by josevalim** [comment]
Can we make Examples have the same style as "Specs"? Also, how does the h3
look like?

Finally, let's add a bit of space before the function name as well.

Thanks for tackling this, it was in my todo for tomorrow. :)


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by milmazz** [comment]
@josevalim Now headings level 2 (e.g Examples) looks like "Specs" title. Added rules for `h3`, `h4`, and `h5`. Finally, there is more space between functions.

screen shot 2015-11-16 at 8 04 20 pm

**Comment by eksperimental** [comment]
How about indenting everything from specs downwards?

**Comment by milmazz** [comment]
@eksperimental What? Why? I do not see the benefit. Your suggestion also apply for mobile devices?

**Comment by Dignifiedquire** [comment]
Please no indent for specs :)

Other than that @milmazz :+1:

**Comment by josevalim** [comment]
:shipit:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@milmazz, let's merge this when you are ready and make a plan for the next release. :)

**Comment by mupkoo** [comment]
I think what @eksperimental is referring is to have it similar to the [Rails docs](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to) which I find easy to read as well.

I am not sure what do you think about increasing the width of the border from 3px to 5px. 

**With of the border - 3px**
screen shot 2015-11-20 at 17 23 37

**With of the border - 5px**
screen shot 2015-11-20 at 17 23 47 1

**Comment by eksperimental** [comment]
@mupkoo thank for clarifying. yes, that's what I meant. Actually i submitted a clarification myself, but by mistake i posted in the original issue ( https://github.com/elixir-lang/ex_doc/issues/419#issuecomment-158094460 )

**Pull request merged**
