### PR TITLE
Limit Travis build matrix to oldest/newest pairs

### PR DESCRIPTION
**Pull request by jparise**
Borrowed from [ecto](https://github.com/elixir-ecto/ecto/blob/master/.travis.yml#L9-L14).

### CODE REVIEW

**Comment by milmazz** [comment]
@jparise What do you think about to increase the newest version to `1.4.0-rc.1`?

**Comment by jparise** [comment]
@milmazz That sounds good to me. Would you like me to make that change as part of this PR, assuming others are good with the bump?

**Comment by ericmj** [comment]
Looks like it would be easier to explicitly include the build pairs we want instead of explicitly excluding.

**Comment by jparise** [comment]
@ericmj, thanks for the idea. I didn't realize that was possible. I tried that approach in the latest commit but it has the side-effect of implicitly including the "default" Elixir/OTP environment. You can see that in this Travis run:

  https://travis-ci.org/elixir-lang/ex_doc/builds/186858880

If anyone knows how to disable that implicit environment, then I think this approach is the winner. Otherwise, I only know how to make the "explicit exclude" approach work.

**Comment by josevalim** [comment]
@jparise I believe you need to have elixir and otp_release at the top, each with one entry and then include the other one.

**Comment by jparise** [comment]
Thanks, @josevalim. That did the trick.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
