### PR TITLE
Remove deprecated timeout option for EarmarkParser

### PR DESCRIPTION
**Pull request by starbelly**

### CODE REVIEW

**Comment by josevalim** [comment]
I would keep it for a while just so we don't impose a very recent earmark version on users. :)

**Comment by starbelly** [comment]
> I would keep it for a while just so we don't impose a very recent earmark version on users. :)

That's fair. Closing this then.

**Comment by eksperimental** [comment]
> > I would keep it for a while just so we don't impose a very recent earmark version on users. :)
> 
> That's fair. Closing this then.

Maybe add a PR with a TODO comment to remove it when certain version of EarMark is required.

**Comment by starbelly** [comment]
> > > I would keep it for a while just so we don't impose a very recent earmark version on users. :)
> > 
> > 
> > That's fair. Closing this then.
> 
> Maybe add a PR with a TODO comment to remove it when certain version of EarMark is required. If the PR can include the source that documents that the feature has been deprecated it will be helpful too.

Will do.

**Pull request closed without merging**
